### ISSUE TITLE
Tracking Issue: XAML Standard Compatibility

### ISSUE THREAD

**Issue by jkoritzinsky** [AvaloniaUI/Avalonia#1282]
Implement a XAML Standard compatibility layer that we ship built-in.

I suggest we use a special namespace/assembly like `Avalonia.Controls.XamlStandard` or `Avalonia.Markup.Xaml.XamlStandard` for separating out classes that are added specifically for compatibility with the standard (such as `RowDefinitionCollection` or `BindingBase`).

XAML Standard Progress:

- [x] Binding
- [ ] BindingBase
- [x] Border
- [x] Button
- [x] ColumnDefinition
- [ ] ColumnDefinitionCollection
- [ ] ComboBox
   * We have now `ComboBox`, but it misses IsEditable mode.
- [x] ContentPresenter
- [x] ControlTemplate
- [x] DataTemplate
- [x] DataTemplateSelector
- [x] DatePicker
- [x] Grid
- [x] Image
- [ ] ListView
   * I think it's similar to `ListBox` but I'm not sure
- [x] ProgressBar
- [ ] ProgressRing
- [x] ResourceDictionary
- [x] RowDefinition
- [ ] RowDefinitionCollection
- [x] Setter
- [x] Slider
- [x] StackPanel
- [x] Style
- [x] TextBlock
- [ ] TextBox
   * Need to add `Placeholder` related properties (instead of/in addition to `Watermark`)
- [x] TimePicker
- [x] ToggleSwitch
  * Basically a re-skinned `ToggleButton`
  * Need `IsOn` `AvaloniaProperty`.
- [x] UserControl
- [ ] WebView
- [x] BindingMode : *{ OneWay, TwoWay }*
- [x] FontStyle : *{ Italic, Normal }*
- [ ] FontWeights : *{Bold, Normal }*
   * We have `FontWeight` as an enum.
- [x] GridLength
- [ ] InputScopeNameValue : *{ Default, Url, Number, TelephoneNumber, Text, Chat, EmailNameOrAddress }*
- [x] Orientation : *{ Vertical, Horizontal }*
- [x] Stretch : *{ Fill, Uniform, UniformToFill }*
- [ ] TextAlignment : *{ Center, End, Start }*
  * Need to define `Start` and `End`. It's `Start` and `End` for LTR and RTL language support.
- [ ] TextWrapping : *{ NoWrap, Wrap, WrapWholeWords }*
  * Missing `WrapWholeWords`
- [x] Thickness
- [x] x:Class
- [x] x:Name
- [x] x:Key
- [x] x:Boolean
- [x]  x:String
- [x] x:Double
- [x] x:Int32

**Comment by grokys** [comment]
Regarding `ComboBox` - I think we should probably just rename `DropDown` to `ComboBox` as it _is_ a standard now, even thought it's wrong ;)

**Comment by maxkatz6** [comment]
@jkoritzinsky 
ComboBox could be checked now :)
And TimePicker/DatePicker/ToggleSwitch soon also.
