### ISSUE TITLE
Tracking issue for all possible XAML compiler warnings

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#13707]
- [x] Obsolete warnings
- [ ] Deprecated/Experimental attributes warnings
- [x] IStyle instance added to the MergedDictionaries (should be added to the Styles collection)
- [x] Duplicate setters
- [ ] Possible null reference exception when adding Transition to the Transitions collection without initializing the collection first (https://github.com/AvaloniaUI/Avalonia/discussions/5899)

Any other ideas?

**Comment by MrJul** [comment]
Duplicate property, two cases:

Attribute + element:
```xaml
<Border Background="Blue">
  <Border.Background>Red</Border.Background>
</Border>
```

Double elements:
```xaml
<Border>
  <Border.Background>Blue</Border.Background>
  <Border.Background>Red</Border.Background>
</Border>
```

Double attributes is already a XML parsing error.

**Comment by MrJul** [comment]
> Possible null reference exception when adding Transition to the Transitions collection without initializing the collection first

It would be nice to have dependency properties able to instantiate collections lazily instead so users don't have to know the whether they should instantiate the collection or not. 

Currently we have two types:
 - Always `null`, e.g. the mentioned `Animatable.Transitions`. Pain: the user must always set the collection, or it's an exception.
 - Always instantiated, e.g. `TextBlock.Inlines`. Pain: allocation if unused (most textblocks), double allocations if set in XAML.

I'll open a separate proposal to discuss that.

**Comment by MrJul** [comment]
`TemplateBinding` used outside of templates. I think I see this one in discussions or Telegram at least once a week :)

**Comment by timunie** [comment]
Used `ContentPresenter` and friends outside ControlTeplate, which is forbidden.

**Comment by stevemonaco** [comment]
Opt-in warnings for `{ReflectionBinding}` usage so devs writing AOT apps can enforce avoiding its usage.

**Comment by maxkatz6** [comment]
XAML compiled should detect following patterns:
```xaml
<TabControl>
    <TabControl.ItemTemplate>
          <DataTempalte>
                 <TabItem Header="{Binding Title}" /> <!-- WARNING:  -->
```

And recommend something like this (possibly, just a link to the documentation/samples):
```xaml
<TabControl ItemsSource="{Binding ...}">
  <TabControl.Styles>
    <Style Selector="TabItem">
      <Setter Property="Header" Value="{Binding Title}"/>
    </Style>
  </TabControl.Styles>
</TabControl>
```

**Comment by Al-Dyachkov** [comment]
Is it possible to add a warning when type declaration in XAML and code behind does not match ?
Common error when a person creates UserControl via template, changes it to ReactiveUserControl<T> and does not immediately modify the code behind to match.

**Comment by maxkatz6** [comment]
@Al-Dyachkov can you bring some example? If types of XAML and code behind are not compatible, there should already be an error (not even a warning). Unless I am missing something.

ReactiveUserControl in code behind and UserControl in XAML should also be fine.

**Comment by Al-Dyachkov** [comment]
@maxkatz6 

xaml
```xml
<reactiveUi:ReactiveUserControl x:TypeArguments="VM" 
                                x:Class="View"
                                x:DataType="VM">
...
</reactiveUi:ReactiveUserControl>
```
code behind 
```cs
public partial class View : UserControl
{ 
}
```

This compiles and even works to some extent because ReactiveUserControl&lt;T&gt; is derived from UserControl, but without any Reactive UI features like activation.

**Comment by workgroupengineering** [comment]
What do you think about pinning this issue so it's easy to find?

**Comment by workgroupengineering** [comment]
I would suggest adding a warning when a DynamicResource is reassigned.  I wasted a whole day troubleshooting a problem due to this.

**Comment by timunie** [comment]
> I would suggest adding a warning when a DynamicResource is reassigned. I wasted a whole day troubleshooting a problem due to this.

@workgroupengineering can you give an example?

**Comment by workgroupengineering** [comment]
> > I would suggest adding a warning when a DynamicResource is reassigned. I wasted a whole day troubleshooting a problem due to this.
> 
> @workgroupengineering can you give an example?

A third-party control defines within it a `DynamicResource` with the same name as the one I created.

```xaml
Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:Dresses.Warehouse"
             x:Class="My.App"
             >
  <!-- "Default" ThemeVariant follows system theme variant. "Dark" or "Light" are other available options. -->

  <Application.Resources>
      <x:Double x:Key="SmallIconSize">18</x:Double>
  </Application.Resources>

  <Application.Styles>
    <FluentTheme />
  </Application.Styles>
</Application>
```

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             x:Class="My.Views.MainView"
             x:ClassModifier="internal"
             >
 <UserContro.Resources>

    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <!-- internally redefines the resource SmallIconSize 24 -->
        <ResourceInclude Source="avares://third_party/third_party_Control.axaml"/>
      </ResourceDictionary.MergedDictionaries>
   </ResourceDictionary>
 </UserContro.Resources>
 <!-- The size is 24 instead of the expected 16, this is because I don't know Third_party_Control.axaml redefines SmallIconSize. -->
 <Rectangle Fill="Red"
             Width="{DynamicResource SmallIconSize}"
             Height="{DynamicResource SmallIconSize}"/>
</UserControl >
```

**Comment by workgroupengineering** [comment]
Add Warnig suppression il xaml like

```xaml

<!--#Suppress-Start: AVX11111 - Reason -->
  ...
<!--#Suppress-End: AVX11111-->

```

**Comment by timunie** [comment]
> A third-party control defines within it a DynamicResource with the same name as the one I created.

That's the exactly what a dynamic resource should do imo 🤔

**Comment by workgroupengineering** [comment]
> > A third-party control defines within it a DynamicResource with the same name as the one I created.
> 
> That's the exactly what a dynamic resource should do imo 🤔 

but if I don't know that it was redefined by another library I will get unexpected behavior.  It just needs to show a warning like SmallIconSize has been redefined in avares://third_party/third_party_Control.axaml

**Comment by maxkatz6** [comment]
Sounds as an expected possibility.

> It just needs to show a warning like SmallIconSize has been redefined

We currently don't have this information. As we don't store such metadata.

> Add Warning suppression il xaml like

Yeah, we need something for that.

**Comment by timunie** [comment]
yet another one (maybe) https://github.com/AvaloniaUI/Avalonia/issues/15593

**Comment by marklam** [comment]
> Is it possible to add a warning when base type declaration in XAML and code behind does not match ? Common error when a person creates UserControl via template, changes it to ReactiveUserControl and does not immediately modify the code behind to match.

As raised in https://github.com/AvaloniaUI/Avalonia/issues/16755, If the class in the code-behind is Control and the XAML is UserControl, it causes an Internal Compiler Error in the XAML compiler, so this mistake can be serious (and very hard to diagnose).
