### ISSUE TITLE
Perf/Memory issue tracker

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2919]
This is my issue for tracking performance and memory optimization across Avalonia.
Most of my findings come from checking ControlCatalog running on x64 Windows using JetBrains dotMemory.

### Renderer:
- [x] `IDeferredRendererLock.TryLock` allocates per-frame (https://github.com/AvaloniaUI/Avalonia/pull/2918)
![image](https://user-images.githubusercontent.com/2588062/64133950-3bb82800-cdda-11e9-9c58-75941d580159.png)
- [x] `Scene` gets cloned completely if any element gets invalidated.
![image](https://user-images.githubusercontent.com/2588062/64133990-a1a4af80-cdda-11e9-8f7b-ebdfb8dd7e62.png)
- [x] `Scene.HitTest` allocates crazy amounts of iterator blocks 
![image](https://user-images.githubusercontent.com/2588062/64133977-8c2f8580-cdda-11e9-9d43-574f78a39689.png)
- [ ] `IVisualNode.Children` cause enumerator boxing due to access via `IReadOnlyList`.
![image](https://user-images.githubusercontent.com/2588062/64134121-73739f80-cddb-11e9-94d4-1817e23dc983.png)
- [x] `RenderLoop` and `DeferredRenderer` allocate new lambdas and lambda closure per-frame (Fixed in https://github.com/AvaloniaUI/Avalonia/pull/2960) 
![image](https://user-images.githubusercontent.com/2588062/64623569-77aa4900-d3e9-11e9-9328-49abd1bb76d5.png)

### Framework:
- [x] `RoutedEvent<T>.AddClassHandler<T>` and `AvaloniaProperty<T>.AddClassHandler<T>` make it very easy (or almost force) to write allocation heavy code. Result below is from moving mouse for few seconds.
![image](https://user-images.githubusercontent.com/2588062/64134498-a9fee980-cdde-11e9-8245-4f2236e425d6.png)
- [x] `InputExtensions.GetInputElementsAt` cause method group allocation per-call. (Fixed in https://github.com/AvaloniaUI/Avalonia/pull/2927).
- [x] `RoutedEvent` is using `Delegate.DynamicInvoke` which is slow (relies fully on reflection) and allocates a lot of garbage. (Fixed in https://github.com/AvaloniaUI/Avalonia/pull/2931 and https://github.com/AvaloniaUI/Avalonia/pull/2943)
- [x] `Logger` API causes each binding and new value to allocate object arrays and box values. 
![image](https://user-images.githubusercontent.com/2588062/64134801-48d91500-cde2-11e9-9c79-627bb002eb2b.png)
![image](https://user-images.githubusercontent.com/2588062/64134807-55f60400-cde2-11e9-9d23-f1e98c039bf1.png)

### Controls:
- [x] `ItemsPresenterBase` using `ItemVirtualizerNone` will cause controls to materialize twice. First materialize will be caused by `PanelCreated` and second by `ItemsChanged`. https://github.com/AvaloniaUI/Avalonia/blob/3b38aea2b9a5ddc4a15cadff7ba74c658c4ba2af/src/Avalonia.Controls/Presenters/ItemsPresenterBase.cs#L223-L225

### Bindings and styling:
- [x] Setters and `AvaloniaObject.Bind` allocate strings for descriptions that most likely will be never seen (in dev tools).
![image](https://user-images.githubusercontent.com/2588062/64134843-ce5cc500-cde2-11e9-825f-9fdb3276a908.png)
- [x] Getting `StyledProperty` default value is always boxing value types. (https://github.com/AvaloniaUI/Avalonia/pull/2935)
![image](https://user-images.githubusercontent.com/2588062/64134902-665aae80-cde3-11e9-84b8-660deaa6ad48.png)
- [x] `PriorityBindingEntry` is allocating two delegates per instance to subscribe to the binding. Can be avoided completely by using `IObserver` interface.  (https://github.com/AvaloniaUI/Avalonia/pull/2931) ![image](https://user-images.githubusercontent.com/2588062/64382139-27bc3280-d035-11e9-8a71-78a6e96e317b.png)

**Comment by MarchingCube** [comment]
@ahopper @kekekeks Wrote down my initial findings, I will add more when I find more time. I am already working on certain issues (marked as `working on a fix`), and I will open PRs slowly as I verify each fix.

**Comment by danwalmsley** [comment]
Wow!

**Comment by grokys** [comment]
Another thing that might be worth investigating: `LightweightObservableBase` always creates a `List<IObserver<T>>` even if it only has a single observer.

We currently have `SingleSubscriberObservableBase` but it might be worth merging the two and only creating the list when there are >1 subscribers.

**Comment by MarchingCube** [comment]
@grokys Hopefully I will get there eventually, right now we still have an order of magnitude worse allocation patterns and I generally pick "easy" things right now that give decent return of investment.
