### ISSUE TITLE
Enable Analyzers 

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#8944]
Add NetAnalyzers  for monitor performance issue

- [x] [CA1304](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1304): Specify CultureInfo #9588
- [x] [CA1802](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1802): Use literals where appropriate #9162
- [x]  ~~[CA1805](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1805): Do not initialize unnecessarily~~ see [comment](https://github.com/AvaloniaUI/Avalonia/pull/9163#issuecomment-1276831556)
- [ ] [CA1806](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1806): Do not ignore method results 
- [ ] [CA1810](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1810): Initialize reference type static fields inline
- [ ] [CA1812](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812): Avoid uninstantiated internal classes 
- [ ] [CA1813](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1813): Avoid unsealed attributes
- [ ] [CA1815](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1815): Override equals and operator equals on value types
- [ ] [CA1819](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1819): Properties should not return arrays
- [x] [CA1820](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820): Test for empty strings using string length #9188 
- [x] [CA1821](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1821): Remove empty Finalizers
- [x] [CA1822](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822): Mark members as static #9189
- [ ] [CA1823](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1823): Avoid unused private fields
- [x] [CA1825](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825): Avoid zero-length array allocations #9166
- [x] [CA1826](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826): Do not use Enumerable methods on indexable collections #9593
- [x] [CA1827](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1827): Do not use Count() or LongCount() when Any() can be used #9593
- [x] [CA1828](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1828): Do not use CountAsync() or LongCountAsync() when AnyAsync() can be used #9593
- [x] [CA1829](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829): Use Length/Count property instead of Count() when available #9593
- [ ] [CA1835](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1835): Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'
- [ ] [CA1838](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1838): Avoid 'StringBuilder' parameters for P/Invokes
- [ ] [CA1844](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1844): Provide memory-based overrides of async methods when subclassing 'Stream'
- [ ] [CA1846](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1846): Prefer 'AsSpan' over 'Substring'
- [x] [CA1847](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1847): Use char literal for a single character lookup #9190
- [ ] [CA1848](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1848): Use the LoggerMessage delegates
- [ ] [CA1849](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1849): Call async methods when in an async method

**Comment by workgroupengineering** [comment]
Can I work on this enhancement?

**Comment by maxkatz6** [comment]
Personally I believe we should have them enabled. 
But most likely it should be enabled slowly project by project with limited number of warnings to avoid noise. 
Less important warnings can be disabled or enabled later in the future.

**Comment by maxkatz6** [comment]
> That is intentional and I don't want you changing blindly to follow CA1819.

That's exactly why I want these rules to be fixed one by one or in small batches. So it can be reviewed and enabled. Otherwise we would stuck in refactorings, huge diffs or tons of warnings. 

> And BTW, there is no way that is a performance issue...

I think it's more an API issue, but still matters mostly in case of public API.

**Comment by maxkatz6** [comment]
> There are also cases where you want zero length arrays so in downstream code you can use iterators without null checks or to about uninitialized variable compile errors. 

This specific rule is not about replacing zero length array with a null object, but replacing it with cached `Array.Empty<int>()` instance. It will reuse same zero length array while `new int[0]` will allocate a new one each call. 

Sometimes `new array` makes sense, if you want to have unique array references, but that's rare.

**Comment by robloo** [comment]
> This specific rule is not about replacing zero length array with a null object, but replacing it with cached Array.Empty<int>() instance

Yea, I misunderstood and saw that with the PR.

**Comment by hez2010** [comment]
Would also like to see Avalonia marking all libraries with `<IsTrimmable>true</IsTrimmable>` and enabling trimming Roslyn analyzer with `<EnableTrimAnalyzer>true</EnableTrimAnalyzer>`.

**Comment by workgroupengineering** [comment]
I'd like to work on [CA1815](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1815), but before I start, I'd like to see if you agree. Here  #8945 you will find the related issue with its benchmarks.

**Comment by maxkatz6** [comment]
Related https://github.com/AvaloniaUI/Avalonia/issues/10119

**Comment by maxkatz6** [comment]
Another analyzer that would be nice to have [CA1852](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1852), possibly as an warning instead of error
